# -*- coding: utf-8 -*-
"""10주.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_yRo3eHOVZB_8KxxiNperNufGlP2oht4

### 한글 깨짐 현상 방지
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

# Commented out IPython magic to ensure Python compatibility.
# %config lnlineBackend.figure_format = 'retina'
!apt -qq -y install fonts-nanum

"""---
한글 텍스트 확인
"""

import matplotlib.pyplot as plt
plt.rc('font', family='NanumGothic')
plt.rcParams['axes.unicode_minus'] = False

plt.figure(figsize=(2, 2))
plt.title('한글')

"""---
## 실전 분석 - 카드 소비 분석

### 데이터 전처리1
"""

import pandas as pd

df = pd.read_csv('/집계구별 일별소비지역별 카드소비패턴.csv', encoding='CP949')
df.head()

df.info()

df = df.rename(columns={
    '가맹점주소광역시도(SIDO)':'시도',
    '가맹점주소시군구(SGG)':'시군구',
    '업종대분류(UPJONG_CLASS1)':'업종',
    '기준일자(YMD)':'기준일자',
    '고객주소집계구별(TOT_REG_CD)':'고객주소집계구별',
    '카드이용금액계(AMT_CORR)':'금액계',
    '카드이용건수계(USECT_CORR)':'이용건수계'
})
df.info()

df1 = df.copy(deep=True)
df1.info()

"""### 데이터 전처리2

결측치 확인
"""

df1.isnull().sum()

"""결측치 행 확인"""

df1[df1.isna().any(axis=1)].head(5)

"""결측치 행 제거"""

df1 = df1.dropna()
print(df1.info())

"""### 데이터 전처리3

'기준일자' 열을 문자열로 변환 astype
"""

df1['기준일자'] = df1['기준일자'].astype('str')
df1.info()

"""'기준일자' 열을 포맷 수정\
20201021 -> 2020-10-21
"""

df1['기준일자2'] = df1['기준일자'].str[:4] + '-' + df1['기준일자'].str[4:6] + '-' + df1['기준일자'].str[6:]
print(df1['기준일자2'])

"""문자열을 날짜타입으로 변경 to_datetime"""

df1['기준일자2'] = pd.to_datetime(df1['기준일자2'])
df1.info()

"""### 데이터 전처리4

날짜 타입에서 년, 월, 일, 요일 계산 필드 추가
"""

df1['년'] = df1['기준일자2'].dt.year
df1['월'] = df1['기준일자2'].dt.month
df1['일'] = df1['기준일자2'].dt.day
df1['숫자요일'] = df1['기준일자2'].dt.dayofweek
df1[['기준일자', '년', '월', '일', '숫자요일']].head(2)

"""숫자 요일을 월~일로 변경"""

weekday_map = {0: '월', 1: '화', 2: '수', 3: '목', 4: '금', 5: '토', 6: '일'}
df1['요일'] = df1['숫자요일'].map(weekday_map)
df1[['기준일자', '년', '월', '일', '숫자요일','요일']].head(2)

"""----
### 데이터 시각화

groupby로 업종별 금액계의 합을 구한다
"""

import matplotlib.pyplot as plt

sum_by_category = df1.groupby('업종')['금액계'].sum()

plt.rc("font",family="NanumBarunGothic")
sum_by_category.plot(kind='bar')
plt.title('업종별 금액계의 합',fontsize=20)
plt.xlabel('업종')
plt.ylabel('금액계 합')
plt.xticks(rotation=45)
plt.show()

import seaborn as sns
sns.barplot(x='업종', y='금액계', data=df1, estimator=sum, ci=None)
plt.xlabel('업종')
plt.ylabel('금액계 합')
plt.title('업종별 금액계의 합')
plt.xticks(rotation=90)
plt.show()

sns.barplot(x='년', y='금액계', data=df1, estimator=sum, ci=None)
plt.xlabel('년')
plt.ylabel('금액계')
plt.title('연도별 금액 총액')
plt.xticks(rotation=0)
plt.show()

sns.barplot(x='월', y='금액계', data=df1, estimator=sum)
plt.xlabel('월')
plt.ylabel('금액계')
plt.title('월별 금액계')
plt.xticks(rotation=0)
plt.show()

sns.barplot(x='요일', y='금액계', data=df1, estimator=sum, ci=None,
            order = ['월', '화', '수', '목', '금', '토', '일'])
plt.xlabel('요일')
plt.ylabel('금액계')
plt.title('요일별 금액합')
plt.xticks(rotation=0)
plt.show()