# -*- coding: utf-8 -*-
"""10주_사전학습_결측치처리1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hFiNVTVncOm8NINU1Q7yrqjxwUwkYNbn

얕은 복사 vs 깊은 복사
"""

import pandas as pd
# 원본 데이터프레임 생성
original_df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

# 얕은 복사
shallow_copy_df = original_df
# 깊은 복사
deep_copy_df = original_df.copy()

# 원본 데이터프레임 수정
original_df.iloc[0, 0] = 100

# 데이터프레임 출력
print("원본 데이터프레임:")
print(original_df)
print("\n얕은 복사 데이터프레임:")
print(shallow_copy_df)
print("\n깊은 복사 데이터프레임:")
print("원본을 수정해도 데이터프레임은 영향을 받지 않음")
print(deep_copy_df)

"""결측값 처리"""

import pandas as pd
import numpy as np

# 예제 데이터프레임 생성
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, 4, 5]
}
df = pd.DataFrame(data)

# 데이터프레임 출력
print("원본 데이터프레임:")
print(df)

"""결측치 확인 isna, isnull"""

# isna 함수 사용
print("isna 함수 사용:")
print(df.isna())

# isnull 함수 사용
print("\nisnull 함수 사용:")
print(df.isnull())

# 1. 데이터프레임에 결측값이 있는지 여부 확인
print("\n데이터프레임에 결측값이 있는지 여부 확인:")
print(df.isna().values.any())

# 2. 열별 결측값 개수 확인
print("\n열별 결측값 개수 확인:")
print(df.isna().sum())

# 3. 결측값의 개수 확인
print("\n전체 데이터프레임에서 결측값의 개수 확인:")
print(df.isna().sum().sum())

# 4. 결측값의 행 확인
print("\n전체 데이터프레임에서 결측값의 행 확인:")
print(df[df.isna().any(axis=1)])

"""결측치 처리 방법
1. 제거
2. 다른 값으로 대체
"""

# 1. 결측값을 포함한 행 삭제
df_dropna = df.dropna()
print("원본 데이터프레임:")
print(df)
print("\n결측값을 포함한 행 삭제:")
print(df_dropna)

# 2. 결측값을 특정 값으로 대체 (평균값 또는 0으로 대체)
df_fillna_mean = df.fillna(df.mean())
print("원본 데이터프레임:")
print(df)
print("\n결측값을 열의 평균값으로 대체:")
print(df_fillna_mean)

# 3. 결측값을 특정 값으로 대체 (열 별로 다른 값으로 대체) mode는 최빈값
values = {'A': df['A'].median(), 'B': df['B'].mode()[0]}
df_fillna_custom = df.fillna(value=values)
print("원본 데이터프레임:")
print(df)
print("\n결측값을 열 별로 다른 값으로 대체:")
print(df_fillna_custom)