# -*- coding: utf-8 -*-
"""10주_사전학습_문자열2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10_8YxEFFBfMm_NjkXarUhpOi6D5q2gJ1

문자열관련 함수
"""

import pandas as pd

# 예제 데이터프레임 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'ID': ['001', '002', 'ABC', '004', '005'],
    'Phone': ['123-456-7890', '987-654-3210', '555-555-5555', '123-456-7890', '987-654-3210'],
    'Age': [25, 30, 35, 40, 22],
    'Email': ['alice@example.com', 'bob@example.com', 'charlie@example.com', 'david@example.com', 'eva@example.com']
}
df = pd.DataFrame(data)
df

"""upper 대문자 ( lower 소문자 )"""

df['Name_upper'] = df['Name'].str.upper()
print("대문자로 변환:")
print(df[['Name', 'Name_upper']])

"""len 문자열 길이"""

df['Name_length'] = df['Name'].str.len()
print("\n문자열 길이 계산:")
print(df[['Name', 'Name_length']])

"""contains 포함여부"""

df['has_a'] = df['Name'].str.contains('a', case=False)
print("\n문자열 포함 여부 확인:")
print(df[['Name', 'has_a']])

"""replace 문자열 치환"""

df['City_replaced'] = df['City'].str.replace(' ', '_')
print("\n문자열 치환:")
print(df[['City', 'City_replaced']])

# ID에서 '0'을 '9'로 치환
df['ID_replaced'] = df['ID'].str.replace('0', '9')
print("ID에서 '0'을 '9'로 치환:")
print(df[['ID', 'ID_replaced']])

"""split 문자열 분할"""

df[['Username', 'Domain']] = df['Email'].str.split('@', expand=True)
print("\n문자열 분할:")
print(df[['Email', 'Username', 'Domain']])

"""Q. 9자리 학번을 각각의 구성 요소(년도, 단대코드, 번호)로 분리"""

# 예제 데이터프레임 생성
data = {
    '학번': ['202100123', '202200456', '202300789', '202400321', '202500654']
}
df1 = pd.DataFrame(data)
df1['입학연도'] = df1['학번'].str[:4]
df1

df1['단대코드'] = df1['학번'].str[4:6]
df1

"""strip 공백제거"""

df['Name_trimmed'] = df['Name'].str.strip()
print("\n문자열 공백 제거:")
print(df[['Name', 'Name_trimmed']])

"""isdigit ID가 숫자로만 이루어져 있는지 확인"""

df['ID_isdigit'] = df['ID'].str.isdigit()
print("\nID가 숫자로만 이루어져 있는지 확인:")
print(df[['ID', 'ID_isdigit']])

"""파일읽기"""

import pandas as pd
df = pd.read_csv("/content/data2.csv", encoding='cp949')
df.head()

df.info()

"""Q Population 필드의 "," 없애기"""

df['Population'] = df['Population'].str.replace(',', '')
df['Population'].head()

df['Population'] =df['Population'].astype(int)
df.info()

df[['City2', 'City3']] = df['City'].str.split('(', expand=True)
df[['City2', 'City3']]

df.head()

df['City2'] = df['City2'].str.strip()
df[['Si', 'Gu',None]] = df['City2'].str.split(' ', expand=True)

df[['Si', 'Gu']]

df[['Si','Population']]

import matplotlib.pyplot as plt
import seaborn as sns

sns.barplot(x='Si', y='Population',data=df)
plt.show

