# -*- coding: utf-8 -*-
"""10주_신용카드분석_학생용.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fm_USG5uYIN1Co2YUB58frpNTX4ad7Dl

맷플립 한글 세팅
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

"""위 코드 실행후 런타임-세션다시시작


"""

import pandas as pd

# 예제 데이터프레임 생성
data = {
    'x': [1, 2, 3, 4, 5],
    'y': [2, 3, 5, 7, 11]
}
df = pd.DataFrame(data)

import matplotlib.pyplot as plt
plt.rc("font",family="NanumBarunGothic")
# 산점도 그리기
plt.scatter(df['x'], df['y'], color='blue', marker='o')
plt.title('그래프')
plt.show()

"""## == 신용카드 소비 분석 ==

# 파일읽기
"""

import pandas as pd

df = pd.read_csv("집계구별 일별소비지역별 카드소비패턴.csv" )
df.head()

"""# Q1 컬럼명 변경하기
'시도','시군구','업종','기준일자','고객주소집계구별','금액계','이용건수계 순으로
"""

##
df.info()

"""깊은 복사"""

df1 = df.copy(deep=True)
df1.info()

"""#전처리
결측치 확인
"""

df1.isnull().sum()

"""결측치 행 확인"""

df1[df1.isna().any(axis=1)].head(5)

"""결측치 제거"""

df1 = df1.dropna()
print(df1.info())

"""# **Q2** '기준일자' 열을 문자열로 변환 astype"""

df1['기준일자'] =df1['기준일자'].astype( )
df1.info()

"""# Q3 '기준일자' 열을 포맷 수정
20201021 => 2020-10-21

"""

#

print(df1['기준일자2'])

"""문자열을 날짜타입으로 변경 to_datetime"""

df1['기준일자2'] = pd.to_datetime(df1['기준일자2'])
df1.info()

"""# Q4 날짜타입에서 년,월,일,요일 계산필드 분리

"""

df1['년'] = df1['기준일자2'].dt.year
#df1['월'] =
#df1['일'] =
#df1['숫자요일'] =
df1[['기준일자','년','월','일','숫자요일']].head(2)

"""요일 숫자를 요일 이름으로"""

weekday_map = {0: '월', 1: '화', 2: '수', 3: '목', 4: '금', 5: '토', 6: '일'}
df1['요일'] = df1['숫자요일'].map(weekday_map)

"""#시각화

업종별 금액의 합 그래프

matplotlib 로

# Q5 groupby 로 업종별 금액계의 합을 구한다

막대그래프를 그린다.
"""

import matplotlib.pyplot as plt

#sum_by_category =

# 그래프 그리기
plt.rc("font",family="NanumBarunGothic")
sum_by_category.plot(kind='bar')
plt.title('업종별 금액계의 합',fontsize=20)
plt.xlabel('업종')
plt.ylabel('금액계 합')
plt.xticks(rotation=45)
plt.show()

"""# Q6 groupby를 사용하지 않고 seaborn

estimator=sum,ci=None
"""

import seaborn as sns
sns.barplot(x='업종', y='금액계', data=df1)
plt.xlabel('업종')
plt.ylabel('금액계 합')
plt.title('업종별 금액계의 합')
plt.xticks(rotation=90)
plt.show()

"""Q7 연도별 금액의 합"""

#sns.barplot()
plt.title('연도별 금액 총액')
plt.xticks(rotation=0)
plt.show()

"""# Q8 월별 금액의 합"""

#sns.barplot( )
plt.title('월별 금액계')
plt.xticks(rotation=0)
plt.show()

"""# Q9 요일별 금액의 평균
order=['월', '화', '수', '목', '금', '토', '일']
"""

#sns.barplot( )
plt.title('요일별 금액합')
plt.xticks(rotation=0)
plt.show()

"""# Q10. 반복문으로 만들어 보자"""

sns.barplot(x='업종', y='금액계', data=df1, estimator=sum, errorbar=None)
plt.show()

sns.barplot(x='년', y='금액계', data=df1, estimator=sum, errorbar=None)
plt.show()

sns.barplot(x='월', y='금액계', data=df1, estimator=sum, errorbar=None)
plt.show()

sns.barplot(x='요일', y='금액계', data=df1, estimator=sum,errorbar=None)
plt.show()