# -*- coding: utf-8 -*-
"""11주_네이버검색어_학생용.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ed4FdqcbUb7eeCdxQxYBFgt0aav6jvS8

Q 맷플립 한글 코드 삽입하기
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

# Commented out IPython magic to ensure Python compatibility.
# %config lnlineBackend.figure_format = 'retina'
!apt -qq -y install fonts-nanum

import matplotlib.pyplot as plt
plt.rc('font', family='NanumGothic')
plt.rcParams['axes.unicode_minus'] = False

#-*- coding: utf-8 -*-
import os
import sys
import urllib.request
client_id = "클아이언트id"
client_secret = "시크릿코드"

keyword1 = "일본"
keyword2 ="제주도"
startDate='2024-01-01'
endDate='2024-05-11'
device='pc'
url = "https://openapi.naver.com/v1/datalab/search";
timeUnit='month'
keywordGroups=[
    {'groupName':keyword1, 'keywords':[keyword1]},
    {'groupName':keyword2, 'keywords':[keyword2]},
]

url = "https://openapi.naver.com/v1/datalab/search";

response_results_all = pd.DataFrame()

body_dict={} #검색 정보를 저장할 변수
body_dict['startDate']=startDate
body_dict['endDate']=endDate
body_dict['timeUnit']=timeUnit
body_dict['keywordGroups']=keywordGroups
body_dict['device']=device

body=str(body_dict).replace("'",'"') # ' 문자로는 에러가 발생해서 " 로 변환

request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
request.add_header("Content-Type","application/json")
response = urllib.request.urlopen(request, data=body.encode("utf-8"))
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)

"""startData, endData

keywordGroups

age
gender

https://developers.naver.com/docs/serviceapi/datalab/search/search.md#통합-검색어-트렌드
"""

import json
result = json.loads(response_body)
print(result)

date = [a['period'] for a in result['results'][0]['data']]
ratio_data1 = [a['ratio'] for a in result['results'][0]['data']]
ratio_data2 = [a['ratio'] for a in result['results'][1]['data']]

import pandas as pd

df = pd.DataFrame(
    {'date':date,
     'searching_result1':ratio_data1,
      'searching_result2':ratio_data2,}
)
df

import seaborn as sns
import matplotlib.pyplot as plt
sns.lineplot(x='date', y='searching_result1', data=df,label='일본')
sns.lineplot(x='date', y='searching_result2', data=df,label='제주도')
plt.title('검색어 트렌드')
plt.xticks(rotation=90)
plt.legend()
plt.show()