# -*- coding: utf-8 -*-
"""w11박스오피스_학생.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLwWmKoNf04DML8GRJ4_jGXqx0GvZawV

Q 맷플립 한글 코드 삽입하기
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

# Commented out IPython magic to ensure Python compatibility.
# %config lnlineBackend.figure_format = 'retina'
!apt -qq -y install fonts-nanum

import matplotlib.pyplot as plt
plt.rc('font', family='NanumGothic')
plt.rcParams['axes.unicode_minus'] = False

"""API 연결하기"""

import requests

"""본인 API 발급 받기"""

apikey = '0d979673d599e6b863814a0a248e2d5a'
tdt = '20230101'
url = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json'

pram = {'key':apikey, 'targetDt':tdt}

resp = requests.get(url, params=pram)
resp

data = resp.json()
print(data)

"""JSON 분석하기

Q showRange 8자리만 가져오기
"""

import pandas as pd
df = pd.DataFrame(data['boxOfficeResult']['dailyBoxOfficeList'])
df = df[['openDt', 'rank','movieNm', 'salesAmt','salesAcc', 'audiCnt', 'audiAcc']]
df['showRange'] = data['boxOfficeResult']['showRange']
df['showRange'] = df['showRange'].str[:8]
df.head(2)

df.columns = ['개봉일','순위','영화명','매출액','누적매출액', '관객수','누적관객수','조회일']
df.info()

"""Q 매출액, 누적매출액, 관객수, 누적관객수 정수로 바꾸기
Q 개봉일, 조회일, 날짜 타입으로 바꾸기.
"""

df = df.astype({'매출액':int, '누적매출액':int, '관객수':int, '누적관객수':int})

df['개봉일'] = pd.to_datetime(df['개봉일'])
df['조회일'] = pd.to_datetime(df['조회일'])
df.info()

#df['요일'] = df['조회일'].dt.day_name()    :영어
df['요일'] = df['조회일'].dt.weekday.map({0:'월', 1:'화', 2:'수',
                                     3:'목',4:'금',5:'토',6:'일'})
df.head(2)

"""apikey, tdt, url 를 매개변수로 박스오피스 데이터프레임을 반환하는 사용자함수 get_boxoffice를 생성하자

-api, tdt를 이용해 url에 접근하기

-json 데이터 받아오기

-데이터 프레임 변경

-필드명 변경

-타입변경
"""

def get_boxoffice(apikey, url, tdt):
  pram = {'key':apikey, 'targetDt':tdt}
  res = requests.get(url, params=pram)
  data = res.json()

  df = pd.DataFrame(data['boxOfficeResult']['dailyBoxOfficeList'])
  df['showRange'] = data['boxOfficeResult']['showRange']
  df['showRange'] = df['showRange'].str[:8]
  df = df[['openDt', 'rank','movieNm', 'salesAmt','salesAcc', 'audiCnt', 'audiAcc', 'showRange']]

  df.columns = ['개봉일','순위','영화명','매출액','누적매출액', '관객수','누적관객수','조회일']

  df = df.astype({'매출액':int, '누적매출액':int, '관객수':int, '누적관객수':int})
  df['개봉일'] = pd.to_datetime(df['개봉일'])
  df['조회일'] = pd.to_datetime(df['조회일'])
  df['요일'] = df['조회일'].dt.weekday.map({0:'월', 1:'화', 2:'수',
                                     3:'목',4:'금',5:'토',6:'일'})
  return df

df_test = get_boxoffice('0d979673d599e6b863814a0a248e2d5a', 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json', '20230101')
df_test

"""위 함수를 get_boxoffice 호출해 보자"""

df = get_boxoffice('0d979673d599e6b863814a0a248e2d5a', 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json', '20230102')
df.head(2)

"""20230101 ~ 20230115 의 데이터를 조회하자."""

date_range = pd.date_range(start='20230101', end='20230115')
date_list = date_range.strftime('%Y%m%d').tolist()

df =pd.DataFrame()
for date in date_list:
  df_day = get_boxoffice('0d979673d599e6b863814a0a248e2d5a', 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json', date)
  df = pd.concat([df, df_day], ignore_index=True)

df.head(20)

df.reset_index(drop=True, inplace=True)
df.head(20)

# df.to_csv('output')

"""Q 관객수 내림차순으로 상위 10개 보기 (sort_values)"""

df.sort_values(['관객수'], ascending=False).head(10)

"""요일별 관객수 보기"""

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10,6))
plt.rc("font",family="NanumBarunGothic")

sns.barplot(data=df, x='요일', y='관객수', hue='요일', ci=None)
plt.xlabel('요일')
plt.ylabel('관객수')
plt.show()

"""영화별 관객수 보기"""

df.columns

plt.figure(figsize=(10,6))
plt.rc("font",family="NanumBarunGothic")

sns.barplot(data=df, x='영화명', y='관객수', hue='영화명', ci=None)
plt.xlabel('영화명')
plt.ylabel('관객수')
plt.xticks(rotation=90)
plt.show()

plt.figure(figsize=(10,6))
plt.rc("font",family="NanumBarunGothic")

sns.barplot(data=df, y='영화명', x='관객수', hue='영화명', ci=None)
plt.ylabel('영화명')
plt.xlabel('관객수')
plt.xticks(rotation=90)
plt.show()

"""영화별 매출액 보기"""

plt.figure(figsize=(10,6))
plt.rc("font",family="NanumBarunGothic")

sns.barplot(data=df, x='영화명', y='매출액', hue='영화명', ci=None)
plt.xlabel('영화명')
plt.ylabel('매출액')
plt.xticks(rotation=90)
plt.show()

"""기타 영화정보 조회"""

url2 = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchWeeklyBoxOfficeList.json'
pram2 = {'key':apikey, 'targetDt':tdt}
resp = requests.get(url2, params=pram2)
resp
data = resp.json()
print(data)

url3 = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json'

pram3 = {'key':apikey, 'movieCd':'20170561'}
resp = requests.get(url3, params=pram3)
resp
data = resp.json()
print(data)