# -*- coding: utf-8 -*-
"""12_위키백과_정답ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189FBGF-ZCMuGHcNTiayRwNSK5pk9zwhr

#Q 위키백과 API
"""

#-*- coding:utf-8 -*-
import urllib3
import json

openApiURL = "http://epretx.etri.re.kr:8000/api/WikiQA"   #Q. url 입력
accessKey = "e3ebfaae-8584-412f-9852-fb81fb0f6b47"    #Q. 본인 API 키 입력 , MyPage에서 확인 가능
question = input('질문을 입력하세요')    # 질문을 사용자로부터 입력

requestJson = {
  "argument": {
    "question": question,
    "type": "ENGINE_TYPE"
  }
}

http = urllib3.PoolManager()
response = http.request(
"POST",
openApiURL,
headers={"Content-Type": "application/json; charset=UTF-8","Authorization": accessKey},
body=json.dumps(requestJson)
)

print("[responseCode] " + str(response.status))
print("[responBody]")
print(str(response.data,"utf-8"))

response_data = response.json()
print(response_data)

print(type(response_data))

response_data.keys()

response_data['return_object'].keys()

"""return data 분석"""

answer_info = response_data['return_object']['WiKiInfo']['AnswerInfo'][0]
answer_info

answer_info['answer']

# 데이터 분석 전문가에 대한 정보 추출

answer_info = response_data['return_object']['WiKiInfo']['AnswerInfo'][0]
print("Rank:", answer_info['rank'])
print("Answer:", answer_info['answer'])
print("Confidence:", answer_info['confidence'])
print("URL:", answer_info['url'][0])

"""# 한글세팅"""

# Commented out IPython magic to ensure Python compatibility.
# %config InlineBackend.figure_format = 'retina'
!apt -qq -y install fonts-nanum
import matplotlib.font_manager as fm
import matplotlib as mpl
fontpath = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'
font = fm.FontProperties(fname=fontpath, size=9)
# mpl.font_manager._rebuild()  # Remove this line as it's likely causing the error
import matplotlib.pyplot as plt
mpl.rcParams['axes.unicode_minus'] = False
plt.rc('font', family='NanumGothic')
plt.rc

import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False

"""# Q 위키데이터로 워드클라우드"""

!pip install wordcloud konlpy
from konlpy.tag import Okt

from konlpy.tag import Okt
import matplotlib.pyplot as plt
from wordcloud import WordCloud

text = answer_info['answer'] #Q 위키데이터 넣기

# 형태소 분석 (Okt 사용)
okt = Okt()
tokens = okt.nouns(text)

# 워드클라우드 생성
wordcloud = WordCloud(
    font_path='/usr/share/fonts/truetype/nanum/NanumGothic.ttf',  # NanumGothic 폰트 경로 설정
    width=800,
    height=800,
    background_color='white'
).generate(' '.join(tokens))

# 워드클라우드 표시
plt.figure(figsize=(8, 8))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

"""#Q 함수 만들기"""

#Q 함수 만들기
def wiki(text) :
  # 형태소 분석 (Okt 사용)
  okt = Okt()
  tokens = okt.nouns(text)

  # 워드클라우드 생성
  wordcloud = WordCloud(
      font_path='/usr/share/fonts/truetype/nanum/NanumGothic.ttf',  # NanumGothic 폰트 경로 설정
      width=800,
      height=800,
      background_color='white'
  ).generate(' '.join(tokens))

  # 워드클라우드 표시
  plt.figure(figsize=(8, 8))
  plt.imshow(wordcloud, interpolation='bilinear')
  plt.axis('off')
  plt.show()

wiki(answer_info['answer'])    #함수호출