# -*- coding: utf-8 -*-
"""사전학습_워드클라우드.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZ1swMQd8soyLRIHWz2IDoyc4DmbeM_M

Q 한글세팅
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf
#실행후 세션리스타트

import matplotlib.pyplot as plt
plt.figure(figsize=(2, 2)  )
plt.rc("font", family="NanumGothic")  #NanumBarunGothic
plt.title('한글') #한글 테스트

"""# 워드클라우드

https://wordcloud.kr/
"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# 텍스트 데이터 예시
text = "데이터 분석 데이터 분석 시각화 파이썬 파이썬 파이썬"

'''
text = """
자연어 처리는 텍스트 데이터를 이해하고 분석하는 데 사용됩니다.
자연어 처리 기술은 워드클라우드와 같은 시각화에도 활용됩니다.
단어의 빈도수를 분석하면 중요한 단어를 파악할 수 있습니다.
파이썬은 자연어 처리와 데이터 분석에 많이 사용되는 언어입니다.
워드클라우드는 단어 빈도를 시각화하는 대표적인 방법입니다.
텍스트 데이터를 분석하면 유의미한 정보와 패턴을 찾을 수 있습니다.
자연어 처리, 워드클라우드, 데이터 분석은 매우 흥미로운 주제입니다.
'''


# 워드클라우드 생성
wordcloud = WordCloud(
    font_path='/usr/share/fonts/truetype/nanum/NanumGothic.ttf',  # NanumGothic 폰트 경로 설정
    # font_path='C:/windows/Fonts/malgun.ttf'
    width=800,
    height=800,
    background_color='white'
).generate(text)

# 워드클라우드 표시
plt.figure(figsize=(8, 8))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

"""#워드 클라우드 + 텍스트분석"""

!pip install wordcloud konlpy
from konlpy.tag import Okt

"""명사 추출하기 (형태소분석기)"""

okt = Okt()
okt.nouns('바보멍청이똥개')

from konlpy.tag import Okt
import matplotlib.pyplot as plt
from wordcloud import WordCloud

# 텍스트 데이터 예시
text = """
자연어 처리는 텍스트 데이터를 이해하고 분석하는 데 사용됩니다.
자연어 처리 기술은 워드클라우드와 같은 시각화에도 활용됩니다.
단어의 빈도수를 분석하면 중요한 단어를 파악할 수 있습니다.
파이썬은 자연어 처리와 데이터 분석에 많이 사용되는 언어입니다.
워드클라우드는 단어 빈도를 시각화하는 대표적인 방법입니다.
텍스트 데이터를 분석하면 유의미한 정보와 패턴을 찾을 수 있습니다.
자연어 처리, 워드클라우드, 데이터 분석은 매우 흥미로운 주제입니다.
"""

# 형태소 분석 (Okt 사용)
okt = Okt()
tokens = okt.nouns(text)

# 워드클라우드 생성
wordcloud = WordCloud(
    font_path='/usr/share/fonts/truetype/nanum/NanumGothic.ttf',  # NanumGothic 폰트 경로 설정
    width=800,
    height=800,
    background_color='white'
).generate(' '.join(tokens))

# 워드클라우드 표시
plt.figure(figsize=(8, 8))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

"""# Mask 사용"""

# 시각화 관련
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
import matplotlib.pyplot as plt
from collections import Counter
from PIL import Image
import numpy as np

icon = Image.open('/content/drive/MyDrive/data_analysis/week 12/그라도넛up.png')
plt.imshow(icon)

mask = Image.new("RGB", icon.size, (255,255,255))
mask.paste(icon,icon)
mask = np.array(mask)

# 워드클라우드 생성
wordcloud = WordCloud(
    font_path='/usr/share/fonts/truetype/nanum/NanumGothic.ttf',  # NanumGothic 폰트 경로 설정
    width=800,
    height=800,
    background_color='white',
    mask=mask
).generate(' '.join(tokens))

# 워드클라우드 표시
plt.figure(figsize=(8, 8))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

from google.colab import drive
drive.mount('/content/drive')

"""#Q 함수 만들기"""

#Q 함수 만들기
def wiki(text, font_path='/usr/share/fonts/truetype/nanum/NanumGothic.ttf'):
    okt = Okt()
    nouns = okt.nouns(text)
    #word_frequencies = Counter(nouns)

    wordcloud = WordCloud(
        font_path=font_path,
        width = 800,
        height = 800,
        background_color='white'
    ).generate(' '.join)

    plt.figure(figsize=(8, 8))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.show()

    return word_frequencies

# 텍스트 데이터 예시
text = """
자연어 처리는 텍스트 데이터를 이해하고 분석하는 데 사용됩니다.
자연어 처리 기술은 워드클라우드와 같은 시각화에도 활용됩니다.
단어의 빈도수를 분석하면 중요한 단어를 파악할 수 있습니다.
파이썬은 자연어 처리와 데이터 분석에 많이 사용되는 언어입니다.
워드클라우드는 단어 빈도를 시각화하는 대표적인 방법입니다.
텍스트 데이터를 분석하면 유의미한 정보와 패턴을 찾을 수 있습니다.
자연어 처리, 워드클라우드, 데이터 분석은 매우 흥미로운 주제입니다.
"""
wiki(text)    #함수호출

# 텍스트 읽기
with open('/content/drive/MyDrive/data_analysis/week 12/클라우드컴퓨팅.txt', 'r', encoding='utf-8') as file:
    text = file.read()
#wiki 함수호출
wiki(text)

